### ISSUE TITLE
Find the path

### ISSUE THREAD

**Issue by rabestro** [rabestro/awk-maze-generator#6]
Given the generated maze as input, find the path and mark it with 👣.

**Comment by mogando668** [comment]
you want me to debug your script or play with the game ?

**Comment by rabestro** [comment]
> you want me to debug your script or play with the game ?

Oh, no :) 
I created the issue just after the completed generations script. 
I am trying to figure out how to write the script to find the path. 
Fortunately, it was pretty easy. :)

**Comment by rabestro** [comment]
> one minor note (just a styling thing not a bug):::

Thank you for your comment! 
I don't know about this and implemented it in the script.
